webFrontend:
  listen: :3000
  sessionKey: random-32-char-string-for-aes256

fitbit:
  clientId: 12AB3C
  clientSecret: place-client-secret-for-app-here

database:
  database:
  host: localhost:3306
  username: fitbit
  password: fitbit
  database: fitbit